"""tabelas de usuarios criada

Revision ID: 136fce0d8174
Revises: 
Create Date: 2022-04-20 10:50:22.553647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '136fce0d8174'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=127), nullable=True),
    sa.Column('last_name', sa.String(length=511), nullable=True),
    sa.Column('email', sa.String(length=80), nullable=True),
    sa.Column('password_hash', sa.String(length=511), nullable=True),
    sa.Column('api_key', sa.String(length=511), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuarios')
    # ### end Alembic commands ###
