"""adicionada propriedade de unique ao email

Revision ID: 7fa91526be28
Revises: 9888e3de4e59
Create Date: 2022-04-20 11:46:56.403803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fa91526be28'
down_revision = '9888e3de4e59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usuarios', 'name',
               existing_type=sa.VARCHAR(length=127),
               nullable=True)
    op.alter_column('usuarios', 'last_name',
               existing_type=sa.VARCHAR(length=511),
               nullable=True)
    op.alter_column('usuarios', 'email',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
    op.alter_column('usuarios', 'password_hash',
               existing_type=sa.VARCHAR(length=511),
               nullable=True)
    op.alter_column('usuarios', 'api_key',
               existing_type=sa.VARCHAR(length=511),
               nullable=True)
    op.create_unique_constraint(None, 'usuarios', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usuarios', type_='unique')
    op.alter_column('usuarios', 'api_key',
               existing_type=sa.VARCHAR(length=511),
               nullable=False)
    op.alter_column('usuarios', 'password_hash',
               existing_type=sa.VARCHAR(length=511),
               nullable=False)
    op.alter_column('usuarios', 'email',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
    op.alter_column('usuarios', 'last_name',
               existing_type=sa.VARCHAR(length=511),
               nullable=False)
    op.alter_column('usuarios', 'name',
               existing_type=sa.VARCHAR(length=127),
               nullable=False)
    # ### end Alembic commands ###
