"""atualizando colunas da tabela para not null

Revision ID: 9888e3de4e59
Revises: 136fce0d8174
Create Date: 2022-04-20 11:04:02.964469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9888e3de4e59'
down_revision = '136fce0d8174'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usuarios', 'name',
               existing_type=sa.VARCHAR(length=127),
               nullable=False)
    op.alter_column('usuarios', 'last_name',
               existing_type=sa.VARCHAR(length=511),
               nullable=False)
    op.alter_column('usuarios', 'email',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
    op.alter_column('usuarios', 'password_hash',
               existing_type=sa.VARCHAR(length=511),
               nullable=False)
    op.alter_column('usuarios', 'api_key',
               existing_type=sa.VARCHAR(length=511),
               nullable=False)
    op.drop_constraint('usuarios_email_key', 'usuarios', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('usuarios_email_key', 'usuarios', ['email'])
    op.alter_column('usuarios', 'api_key',
               existing_type=sa.VARCHAR(length=511),
               nullable=True)
    op.alter_column('usuarios', 'password_hash',
               existing_type=sa.VARCHAR(length=511),
               nullable=True)
    op.alter_column('usuarios', 'email',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
    op.alter_column('usuarios', 'last_name',
               existing_type=sa.VARCHAR(length=511),
               nullable=True)
    op.alter_column('usuarios', 'name',
               existing_type=sa.VARCHAR(length=127),
               nullable=True)
    # ### end Alembic commands ###
